using System;
using System.Collections.Generic;
using System.Linq;
using ISILab.Commons.Extensions;
using ISILab.Commons.JsonNet;
using ISILab.Extensions;
using ISILab.LBS.Plugin.Core.Settings;
using LBS.Components;
using Newtonsoft.Json;
using UnityEngine;
using static ISILab.LBS.Plugin.MapTools.Generators.LBSGeneratorRule;

namespace ISILab.LBS.Plugin.MapTools.Generators
{
    public class Generator3D
    {
        
        #region FIELDS
        [SerializeField]
        public LBSGenerator3DSettings settings = new LBSGenerator3DSettings();

        [JsonRequired, SerializeReference]
        private List<LBSGeneratorRule> rules = new List<LBSGeneratorRule>();
        #endregion
        
        #region METHODS
        public void AddRule(LBSGeneratorRule rule)
        {
            rules.Add(rule);
            rule.generator3D = this;
        }

        public T GetRule<T>() where T : LBSGeneratorRule
        {
            return rules.OfType<T>().FirstOrDefault();
        }

        [System.Obsolete("Unnecesary usage of obsolete class. Consider deleting this method or creating a new extension.")]
        public T GetRule<T>( List<LBSGeneratorRule> otherRules) where T : LBSGeneratorRule
        {
            return otherRules.OfType<T>().FirstOrDefault();
        }

        public void RemoveRule(LBSGeneratorRule rule)
        {
            if (rules.Remove(rule))
                rule.generator3D = null;
        }

        public bool CheckIfIsPosible(LBSLayer layer)
        {
            foreach (var rule in rules)
            {
                var msg = "";
                var msgs = rule.CheckViability(layer); 
                if (msgs.Count > 0)
                {
                    Debug.Log(msg);
                    return false;
                }
            }
            return true;
        }

        /// <summary>
        /// Generates a game object that contains all the content generated by a given layer
        /// </summary>
        /// <param name="layer">An LBSLayer containing the data to be generated</param>
        /// <param name="rules">The rules that are applied to the generation</param>
        /// <param name="settings">Settings passed from the Generator</param>
        /// <returns>A tuple containing the game object and a list of messages |
        /// On successful generation: return gameObject, and empty list
        /// On failed generation: return gameObject and a list full of error message</returns>
        public Tuple<GameObject, List<GeneratedGO>> Generate(LBSLayer layer,List<LBSGeneratorRule> rules, LBSGenerator3DSettings settings)
        {
            // each generation should have a message to indicate the reasons for failed generations
            List<GeneratedGO> gos = new List<GeneratedGO>();
            
            var name = settings.name;
            var parent = new GameObject(name);
            this.rules = rules;

            parent.transform.position = settings.position;
            
            if (this.rules.Count <= 0)
            {
                gos.Add(new GeneratedGO(null, "[ISILab]: Generator contain 0 rules to generate map"));
                return Tuple.Create(parent, gos);
            }
            
            for (int i = 0; i < this.rules.Count; i++)
            {
                var ruleParent = rules[i].Generate(layer, settings);

                if (ruleParent.go == null)
                {
                    gos.Add(new GeneratedGO(null, ruleParent.message));
                    continue;
                }
                else if (ruleParent.message != null)
                {
                    gos.Add(ruleParent);
                    continue;
                }

                    ruleParent.go.SetParent(parent);
            }
            return Tuple.Create(parent, gos);
        }
        #endregion
    }
}