### YamlMime:ManagedReference
items:
- uid: ISILab.LBS.Plugin.Core.Settings.Editor
  commentId: N:ISILab.LBS.Plugin.Core.Settings.Editor
  id: ISILab.LBS.Plugin.Core.Settings.Editor
  children:
  - ISILab.LBS.Plugin.Core.Settings.Editor.LBSCallbacks
  - ISILab.LBS.Plugin.Core.Settings.Editor.SettingsEditor
  - ISILab.LBS.Plugin.Core.Settings.Editor.Startup
  langs:
  - csharp
  - vb
  name: ISILab.LBS.Plugin.Core.Settings.Editor
  nameWithType: ISILab.LBS.Plugin.Core.Settings.Editor
  fullName: ISILab.LBS.Plugin.Core.Settings.Editor
  type: Namespace
  assemblies:
  - LBS.Editor
references:
- uid: ISILab.LBS.Plugin.Core.Settings.Editor.LBSCallbacks
  commentId: T:ISILab.LBS.Plugin.Core.Settings.Editor.LBSCallbacks
  isExternal: true
  href: ISILab.LBS.Plugin.Core.Settings.Editor.LBSCallbacks.html
  name: LBSCallbacks
  nameWithType: LBSCallbacks
  fullName: ISILab.LBS.Plugin.Core.Settings.Editor.LBSCallbacks
- uid: ISILab.LBS.Plugin.Core.Settings.Editor.SettingsEditor
  commentId: T:ISILab.LBS.Plugin.Core.Settings.Editor.SettingsEditor
  isExternal: true
  href: ISILab.LBS.Plugin.Core.Settings.Editor.SettingsEditor.html
  name: SettingsEditor
  nameWithType: SettingsEditor
  fullName: ISILab.LBS.Plugin.Core.Settings.Editor.SettingsEditor
- uid: ISILab.LBS.Plugin.Core.Settings.Editor.Startup
  commentId: T:ISILab.LBS.Plugin.Core.Settings.Editor.Startup
  isExternal: true
  href: ISILab.LBS.Plugin.Core.Settings.Editor.Startup.html
  name: Startup
  nameWithType: Startup
  fullName: ISILab.LBS.Plugin.Core.Settings.Editor.Startup
shouldSkipMarkup: true
