### YamlMime:ManagedReference
items:
- uid: ISILab.LBS.Editor.EvaluatorConfigurationEditor
  commentId: T:ISILab.LBS.Editor.EvaluatorConfigurationEditor
  id: EvaluatorConfigurationEditor
  parent: ISILab.LBS.Editor
  children:
  - ISILab.LBS.Editor.EvaluatorConfigurationEditor.#ctor
  - ISILab.LBS.Editor.EvaluatorConfigurationEditor.CreateInspectorGUI
  langs:
  - csharp
  - vb
  name: EvaluatorConfigurationEditor
  nameWithType: EvaluatorConfigurationEditor
  fullName: ISILab.LBS.Editor.EvaluatorConfigurationEditor
  type: Class
  assemblies:
  - LBS.Editor
  namespace: ISILab.LBS.Editor
  syntax:
    content: 'public class EvaluatorConfigurationEditor : Editor'
    content.vb: Public Class EvaluatorConfigurationEditor Inherits Editor
  inheritance:
  - System.Object
- uid: ISILab.LBS.Editor.EvaluatorConfigurationEditor.CreateInspectorGUI
  commentId: M:ISILab.LBS.Editor.EvaluatorConfigurationEditor.CreateInspectorGUI
  id: CreateInspectorGUI
  parent: ISILab.LBS.Editor.EvaluatorConfigurationEditor
  langs:
  - csharp
  - vb
  name: CreateInspectorGUI()
  nameWithType: EvaluatorConfigurationEditor.CreateInspectorGUI()
  fullName: ISILab.LBS.Editor.EvaluatorConfigurationEditor.CreateInspectorGUI()
  type: Method
  assemblies:
  - LBS.Editor
  namespace: ISILab.LBS.Editor
  example: []
  syntax:
    content: public override VisualElement CreateInspectorGUI()
    return:
      type: UnityEngine.UIElements.VisualElement
    content.vb: Public Overrides Function CreateInspectorGUI() As VisualElement
  overload: ISILab.LBS.Editor.EvaluatorConfigurationEditor.CreateInspectorGUI*
- uid: ISILab.LBS.Editor.EvaluatorConfigurationEditor.#ctor
  commentId: M:ISILab.LBS.Editor.EvaluatorConfigurationEditor.#ctor
  id: '#ctor'
  parent: ISILab.LBS.Editor.EvaluatorConfigurationEditor
  langs:
  - csharp
  - vb
  name: EvaluatorConfigurationEditor()
  nameWithType: EvaluatorConfigurationEditor.EvaluatorConfigurationEditor()
  fullName: ISILab.LBS.Editor.EvaluatorConfigurationEditor.EvaluatorConfigurationEditor()
  type: Constructor
  assemblies:
  - LBS.Editor
  namespace: ISILab.LBS.Editor
  syntax:
    content: public EvaluatorConfigurationEditor()
    content.vb: Public Sub New()
  overload: ISILab.LBS.Editor.EvaluatorConfigurationEditor.#ctor*
  nameWithType.vb: EvaluatorConfigurationEditor.New()
  fullName.vb: ISILab.LBS.Editor.EvaluatorConfigurationEditor.New()
  name.vb: New()
references:
- uid: ISILab.LBS.Editor
  commentId: N:ISILab.LBS.Editor
  isExternal: true
  href: ISILab.html
  name: ISILab.LBS.Editor
  nameWithType: ISILab.LBS.Editor
  fullName: ISILab.LBS.Editor
  spec.csharp:
  - uid: ISILab
    name: ISILab
    isExternal: true
    href: ISILab.html
  - name: .
  - uid: ISILab.LBS
    name: LBS
    isExternal: true
    href: ISILab.LBS.html
  - name: .
  - uid: ISILab.LBS.Editor
    name: Editor
    isExternal: true
    href: ISILab.LBS.Editor.html
  spec.vb:
  - uid: ISILab
    name: ISILab
    isExternal: true
    href: ISILab.html
  - name: .
  - uid: ISILab.LBS
    name: LBS
    isExternal: true
    href: ISILab.LBS.html
  - name: .
  - uid: ISILab.LBS.Editor
    name: Editor
    isExternal: true
    href: ISILab.LBS.Editor.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ISILab.LBS.Editor.EvaluatorConfigurationEditor.CreateInspectorGUI*
  commentId: Overload:ISILab.LBS.Editor.EvaluatorConfigurationEditor.CreateInspectorGUI
  isExternal: true
  href: ISILab.LBS.Editor.EvaluatorConfigurationEditor.html#ISILab_LBS_Editor_EvaluatorConfigurationEditor_CreateInspectorGUI
  name: CreateInspectorGUI
  nameWithType: EvaluatorConfigurationEditor.CreateInspectorGUI
  fullName: ISILab.LBS.Editor.EvaluatorConfigurationEditor.CreateInspectorGUI
- uid: UnityEngine.UIElements.VisualElement
  isExternal: true
  name: VisualElement
  nameWithType: VisualElement
  fullName: UnityEngine.UIElements.VisualElement
- uid: ISILab.LBS.Editor.EvaluatorConfigurationEditor.#ctor*
  commentId: Overload:ISILab.LBS.Editor.EvaluatorConfigurationEditor.#ctor
  isExternal: true
  href: ISILab.LBS.Editor.EvaluatorConfigurationEditor.html#ISILab_LBS_Editor_EvaluatorConfigurationEditor__ctor
  name: EvaluatorConfigurationEditor
  nameWithType: EvaluatorConfigurationEditor.EvaluatorConfigurationEditor
  fullName: ISILab.LBS.Editor.EvaluatorConfigurationEditor.EvaluatorConfigurationEditor
  nameWithType.vb: EvaluatorConfigurationEditor.New
  fullName.vb: ISILab.LBS.Editor.EvaluatorConfigurationEditor.New
  name.vb: New
shouldSkipMarkup: true
