### YamlMime:ManagedReference
items:
- uid: ISILab.LBS.Plugin.Core.Settings
  commentId: N:ISILab.LBS.Plugin.Core.Settings
  id: ISILab.LBS.Plugin.Core.Settings
  children:
  - ISILab.LBS.Plugin.Core.Settings.LBSGenerator3DSettings
  - ISILab.LBS.Plugin.Core.Settings.LBSLog
  - ISILab.LBS.Plugin.Core.Settings.LBSSettings
  - ISILab.LBS.Plugin.Core.Settings.LBSSettings.General
  - ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface
  - ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme
  - ISILab.LBS.Plugin.Core.Settings.LBSSettings.Paths
  - ISILab.LBS.Plugin.Core.Settings.LBSSettings.Test
  - ISILab.LBS.Plugin.Core.Settings.OptimizationGenMode
  langs:
  - csharp
  - vb
  name: ISILab.LBS.Plugin.Core.Settings
  nameWithType: ISILab.LBS.Plugin.Core.Settings
  fullName: ISILab.LBS.Plugin.Core.Settings
  type: Namespace
  assemblies:
  - LBS
references:
- uid: ISILab.LBS.Plugin.Core.Settings.LBSLog
  commentId: T:ISILab.LBS.Plugin.Core.Settings.LBSLog
  parent: ISILab.LBS.Plugin.Core.Settings
  isExternal: true
  href: ISILab.LBS.Plugin.Core.Settings.LBSLog.html
  name: LBSLog
  nameWithType: LBSLog
  fullName: ISILab.LBS.Plugin.Core.Settings.LBSLog
- uid: ISILab.LBS.Plugin.Core.Settings.OptimizationGenMode
  commentId: T:ISILab.LBS.Plugin.Core.Settings.OptimizationGenMode
  parent: ISILab.LBS.Plugin.Core.Settings
  isExternal: true
  href: ISILab.LBS.Plugin.Core.Settings.OptimizationGenMode.html
  name: OptimizationGenMode
  nameWithType: OptimizationGenMode
  fullName: ISILab.LBS.Plugin.Core.Settings.OptimizationGenMode
- uid: ISILab.LBS.Plugin.Core.Settings.LBSGenerator3DSettings
  commentId: T:ISILab.LBS.Plugin.Core.Settings.LBSGenerator3DSettings
  parent: ISILab.LBS.Plugin.Core.Settings
  isExternal: true
  href: ISILab.LBS.Plugin.Core.Settings.LBSGenerator3DSettings.html
  name: LBSGenerator3DSettings
  nameWithType: LBSGenerator3DSettings
  fullName: ISILab.LBS.Plugin.Core.Settings.LBSGenerator3DSettings
- uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings
  commentId: T:ISILab.LBS.Plugin.Core.Settings.LBSSettings
  parent: ISILab.LBS.Plugin.Core.Settings
  isExternal: true
  href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.html
  name: LBSSettings
  nameWithType: LBSSettings
  fullName: ISILab.LBS.Plugin.Core.Settings.LBSSettings
- uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Test
  commentId: T:ISILab.LBS.Plugin.Core.Settings.LBSSettings.Test
  parent: ISILab.LBS.Plugin.Core.Settings
  isExternal: true
  href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.html
  name: LBSSettings.Test
  nameWithType: LBSSettings.Test
  fullName: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Test
  spec.csharp:
  - uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings
    name: LBSSettings
    isExternal: true
    href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.html
  - name: .
  - uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Test
    name: Test
    isExternal: true
    href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Test.html
  spec.vb:
  - uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings
    name: LBSSettings
    isExternal: true
    href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.html
  - name: .
  - uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Test
    name: Test
    isExternal: true
    href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Test.html
- uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings.General
  commentId: T:ISILab.LBS.Plugin.Core.Settings.LBSSettings.General
  parent: ISILab.LBS.Plugin.Core.Settings
  isExternal: true
  href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.html
  name: LBSSettings.General
  nameWithType: LBSSettings.General
  fullName: ISILab.LBS.Plugin.Core.Settings.LBSSettings.General
  spec.csharp:
  - uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings
    name: LBSSettings
    isExternal: true
    href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.html
  - name: .
  - uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings.General
    name: General
    isExternal: true
    href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.General.html
  spec.vb:
  - uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings
    name: LBSSettings
    isExternal: true
    href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.html
  - name: .
  - uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings.General
    name: General
    isExternal: true
    href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.General.html
- uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Paths
  commentId: T:ISILab.LBS.Plugin.Core.Settings.LBSSettings.Paths
  parent: ISILab.LBS.Plugin.Core.Settings
  isExternal: true
  href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.html
  name: LBSSettings.Paths
  nameWithType: LBSSettings.Paths
  fullName: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Paths
  spec.csharp:
  - uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings
    name: LBSSettings
    isExternal: true
    href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.html
  - name: .
  - uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Paths
    name: Paths
    isExternal: true
    href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Paths.html
  spec.vb:
  - uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings
    name: LBSSettings
    isExternal: true
    href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.html
  - name: .
  - uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Paths
    name: Paths
    isExternal: true
    href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Paths.html
- uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface
  commentId: T:ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface
  parent: ISILab.LBS.Plugin.Core.Settings
  isExternal: true
  href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.html
  name: LBSSettings.Interface
  nameWithType: LBSSettings.Interface
  fullName: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface
  spec.csharp:
  - uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings
    name: LBSSettings
    isExternal: true
    href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.html
  - name: .
  - uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface
    name: Interface
    isExternal: true
    href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.html
  spec.vb:
  - uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings
    name: LBSSettings
    isExternal: true
    href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.html
  - name: .
  - uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface
    name: Interface
    isExternal: true
    href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.html
- uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme
  commentId: T:ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme
  parent: ISILab.LBS.Plugin.Core.Settings
  isExternal: true
  href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.html
  name: LBSSettings.Interface.InterfaceTheme
  nameWithType: LBSSettings.Interface.InterfaceTheme
  fullName: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme
  spec.csharp:
  - uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings
    name: LBSSettings
    isExternal: true
    href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.html
  - name: .
  - uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface
    name: Interface
    isExternal: true
    href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.html
  - name: .
  - uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme
    name: InterfaceTheme
    isExternal: true
    href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme.html
  spec.vb:
  - uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings
    name: LBSSettings
    isExternal: true
    href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.html
  - name: .
  - uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface
    name: Interface
    isExternal: true
    href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.html
  - name: .
  - uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme
    name: InterfaceTheme
    isExternal: true
    href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme.html
- uid: ISILab.LBS.Plugin.Core.Settings
  commentId: N:ISILab.LBS.Plugin.Core.Settings
  isExternal: true
  href: ISILab.html
  name: ISILab.LBS.Plugin.Core.Settings
  nameWithType: ISILab.LBS.Plugin.Core.Settings
  fullName: ISILab.LBS.Plugin.Core.Settings
  spec.csharp:
  - uid: ISILab
    name: ISILab
    isExternal: true
    href: ISILab.html
  - name: .
  - uid: ISILab.LBS
    name: LBS
    isExternal: true
    href: ISILab.LBS.html
  - name: .
  - uid: ISILab.LBS.Plugin
    name: Plugin
    isExternal: true
    href: ISILab.LBS.Plugin.html
  - name: .
  - uid: ISILab.LBS.Plugin.Core
    name: Core
    isExternal: true
    href: ISILab.LBS.Plugin.Core.html
  - name: .
  - uid: ISILab.LBS.Plugin.Core.Settings
    name: Settings
    isExternal: true
    href: ISILab.LBS.Plugin.Core.Settings.html
  spec.vb:
  - uid: ISILab
    name: ISILab
    isExternal: true
    href: ISILab.html
  - name: .
  - uid: ISILab.LBS
    name: LBS
    isExternal: true
    href: ISILab.LBS.html
  - name: .
  - uid: ISILab.LBS.Plugin
    name: Plugin
    isExternal: true
    href: ISILab.LBS.Plugin.html
  - name: .
  - uid: ISILab.LBS.Plugin.Core
    name: Core
    isExternal: true
    href: ISILab.LBS.Plugin.Core.html
  - name: .
  - uid: ISILab.LBS.Plugin.Core.Settings
    name: Settings
    isExternal: true
    href: ISILab.LBS.Plugin.Core.Settings.html
shouldSkipMarkup: true
