### YamlMime:ManagedReference
items:
- uid: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration
  commentId: T:ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration
  id: MAPEliteConfiguration
  parent: ISILab.LBS.AI.Assistants.Editor
  children:
  - ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.#ctor
  - ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.Calculate
  - ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.Continue
  - ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.GetPresset
  - ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.OnCalculate
  - ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.OnContinue
  - ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.OnPressetChange
  - ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.OnUndo
  - ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.Undo
  langs:
  - csharp
  - vb
  name: MAPEliteConfiguration
  nameWithType: MAPEliteConfiguration
  fullName: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration
  type: Class
  assemblies:
  - LBS.Editor
  namespace: ISILab.LBS.AI.Assistants.Editor
  syntax:
    content: 'public class MAPEliteConfiguration : VisualElement'
    content.vb: Public Class MAPEliteConfiguration Inherits VisualElement
  inheritance:
  - System.Object
- uid: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.OnCalculate
  commentId: F:ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.OnCalculate
  id: OnCalculate
  parent: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration
  langs:
  - csharp
  - vb
  name: OnCalculate
  nameWithType: MAPEliteConfiguration.OnCalculate
  fullName: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.OnCalculate
  type: Field
  assemblies:
  - LBS.Editor
  namespace: ISILab.LBS.AI.Assistants.Editor
  syntax:
    content: public Action OnCalculate
    return:
      type: System.Action
    content.vb: Public OnCalculate As Action
- uid: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.OnContinue
  commentId: F:ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.OnContinue
  id: OnContinue
  parent: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration
  langs:
  - csharp
  - vb
  name: OnContinue
  nameWithType: MAPEliteConfiguration.OnContinue
  fullName: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.OnContinue
  type: Field
  assemblies:
  - LBS.Editor
  namespace: ISILab.LBS.AI.Assistants.Editor
  syntax:
    content: public Action OnContinue
    return:
      type: System.Action
    content.vb: Public OnContinue As Action
- uid: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.OnUndo
  commentId: F:ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.OnUndo
  id: OnUndo
  parent: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration
  langs:
  - csharp
  - vb
  name: OnUndo
  nameWithType: MAPEliteConfiguration.OnUndo
  fullName: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.OnUndo
  type: Field
  assemblies:
  - LBS.Editor
  namespace: ISILab.LBS.AI.Assistants.Editor
  syntax:
    content: public Action OnUndo
    return:
      type: System.Action
    content.vb: Public OnUndo As Action
- uid: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.OnPressetChange
  commentId: F:ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.OnPressetChange
  id: OnPressetChange
  parent: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration
  langs:
  - csharp
  - vb
  name: OnPressetChange
  nameWithType: MAPEliteConfiguration.OnPressetChange
  fullName: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.OnPressetChange
  type: Field
  assemblies:
  - LBS.Editor
  namespace: ISILab.LBS.AI.Assistants.Editor
  syntax:
    content: public Action<string> OnPressetChange
    return:
      type: System.Action{System.String}
    content.vb: Public OnPressetChange As Action(Of String)
- uid: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.#ctor
  commentId: M:ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.#ctor
  id: '#ctor'
  parent: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration
  langs:
  - csharp
  - vb
  name: MAPEliteConfiguration()
  nameWithType: MAPEliteConfiguration.MAPEliteConfiguration()
  fullName: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.MAPEliteConfiguration()
  type: Constructor
  assemblies:
  - LBS.Editor
  namespace: ISILab.LBS.AI.Assistants.Editor
  syntax:
    content: public MAPEliteConfiguration()
    content.vb: Public Sub New()
  overload: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.#ctor*
  nameWithType.vb: MAPEliteConfiguration.New()
  fullName.vb: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.New()
  name.vb: New()
- uid: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.Calculate
  commentId: M:ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.Calculate
  id: Calculate
  parent: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration
  langs:
  - csharp
  - vb
  name: Calculate()
  nameWithType: MAPEliteConfiguration.Calculate()
  fullName: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.Calculate()
  type: Method
  assemblies:
  - LBS.Editor
  namespace: ISILab.LBS.AI.Assistants.Editor
  syntax:
    content: public void Calculate()
    content.vb: Public Sub Calculate()
  overload: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.Calculate*
- uid: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.Continue
  commentId: M:ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.Continue
  id: Continue
  parent: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration
  langs:
  - csharp
  - vb
  name: Continue()
  nameWithType: MAPEliteConfiguration.Continue()
  fullName: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.Continue()
  type: Method
  assemblies:
  - LBS.Editor
  namespace: ISILab.LBS.AI.Assistants.Editor
  syntax:
    content: public void Continue()
    content.vb: Public Sub [Continue]()
  overload: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.Continue*
- uid: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.Undo
  commentId: M:ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.Undo
  id: Undo
  parent: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration
  langs:
  - csharp
  - vb
  name: Undo()
  nameWithType: MAPEliteConfiguration.Undo()
  fullName: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.Undo()
  type: Method
  assemblies:
  - LBS.Editor
  namespace: ISILab.LBS.AI.Assistants.Editor
  syntax:
    content: public void Undo()
    content.vb: Public Sub Undo()
  overload: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.Undo*
- uid: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.GetPresset
  commentId: M:ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.GetPresset
  id: GetPresset
  parent: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration
  langs:
  - csharp
  - vb
  name: GetPresset()
  nameWithType: MAPEliteConfiguration.GetPresset()
  fullName: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.GetPresset()
  type: Method
  assemblies:
  - LBS.Editor
  namespace: ISILab.LBS.AI.Assistants.Editor
  syntax:
    content: public MAPElitesPreset GetPresset()
    return:
      type: ISILab.LBS.AI.Categorization.MAPElitesPreset
    content.vb: Public Function GetPresset() As MAPElitesPreset
  overload: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.GetPresset*
references:
- uid: ISILab.LBS.AI.Assistants.Editor
  commentId: N:ISILab.LBS.AI.Assistants.Editor
  isExternal: true
  href: ISILab.html
  name: ISILab.LBS.AI.Assistants.Editor
  nameWithType: ISILab.LBS.AI.Assistants.Editor
  fullName: ISILab.LBS.AI.Assistants.Editor
  spec.csharp:
  - uid: ISILab
    name: ISILab
    isExternal: true
    href: ISILab.html
  - name: .
  - uid: ISILab.LBS
    name: LBS
    isExternal: true
    href: ISILab.LBS.html
  - name: .
  - uid: ISILab.LBS.AI
    name: AI
    isExternal: true
    href: ISILab.LBS.AI.html
  - name: .
  - uid: ISILab.LBS.AI.Assistants
    name: Assistants
    isExternal: true
    href: ISILab.LBS.AI.Assistants.html
  - name: .
  - uid: ISILab.LBS.AI.Assistants.Editor
    name: Editor
    isExternal: true
    href: ISILab.LBS.AI.Assistants.Editor.html
  spec.vb:
  - uid: ISILab
    name: ISILab
    isExternal: true
    href: ISILab.html
  - name: .
  - uid: ISILab.LBS
    name: LBS
    isExternal: true
    href: ISILab.LBS.html
  - name: .
  - uid: ISILab.LBS.AI
    name: AI
    isExternal: true
    href: ISILab.LBS.AI.html
  - name: .
  - uid: ISILab.LBS.AI.Assistants
    name: Assistants
    isExternal: true
    href: ISILab.LBS.AI.Assistants.html
  - name: .
  - uid: ISILab.LBS.AI.Assistants.Editor
    name: Editor
    isExternal: true
    href: ISILab.LBS.AI.Assistants.Editor.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Action
  commentId: T:System.Action
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.action
  name: Action
  nameWithType: Action
  fullName: System.Action
- uid: System.Action{System.String}
  commentId: T:System.Action{System.String}
  parent: System
  definition: System.Action`1
  href: https://learn.microsoft.com/dotnet/api/system.action-1
  name: Action<string>
  nameWithType: Action<string>
  fullName: System.Action<string>
  nameWithType.vb: Action(Of String)
  fullName.vb: System.Action(Of String)
  name.vb: Action(Of String)
  spec.csharp:
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: System.Action`1
  commentId: T:System.Action`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.action-1
  name: Action<T>
  nameWithType: Action<T>
  fullName: System.Action<T>
  nameWithType.vb: Action(Of T)
  fullName.vb: System.Action(Of T)
  name.vb: Action(Of T)
  spec.csharp:
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.#ctor*
  commentId: Overload:ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.#ctor
  isExternal: true
  href: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.html#ISILab_LBS_AI_Assistants_Editor_MAPEliteConfiguration__ctor
  name: MAPEliteConfiguration
  nameWithType: MAPEliteConfiguration.MAPEliteConfiguration
  fullName: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.MAPEliteConfiguration
  nameWithType.vb: MAPEliteConfiguration.New
  fullName.vb: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.New
  name.vb: New
- uid: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.Calculate*
  commentId: Overload:ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.Calculate
  isExternal: true
  href: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.html#ISILab_LBS_AI_Assistants_Editor_MAPEliteConfiguration_Calculate
  name: Calculate
  nameWithType: MAPEliteConfiguration.Calculate
  fullName: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.Calculate
- uid: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.Continue*
  commentId: Overload:ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.Continue
  isExternal: true
  href: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.html#ISILab_LBS_AI_Assistants_Editor_MAPEliteConfiguration_Continue
  name: Continue
  nameWithType: MAPEliteConfiguration.Continue
  fullName: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.Continue
- uid: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.Undo*
  commentId: Overload:ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.Undo
  isExternal: true
  href: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.html#ISILab_LBS_AI_Assistants_Editor_MAPEliteConfiguration_Undo
  name: Undo
  nameWithType: MAPEliteConfiguration.Undo
  fullName: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.Undo
- uid: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.GetPresset*
  commentId: Overload:ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.GetPresset
  isExternal: true
  href: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.html#ISILab_LBS_AI_Assistants_Editor_MAPEliteConfiguration_GetPresset
  name: GetPresset
  nameWithType: MAPEliteConfiguration.GetPresset
  fullName: ISILab.LBS.AI.Assistants.Editor.MAPEliteConfiguration.GetPresset
- uid: ISILab.LBS.AI.Categorization.MAPElitesPreset
  commentId: T:ISILab.LBS.AI.Categorization.MAPElitesPreset
  parent: ISILab.LBS.AI.Categorization
  isExternal: true
  href: ISILab.LBS.AI.Categorization.MAPElitesPreset.html
  name: MAPElitesPreset
  nameWithType: MAPElitesPreset
  fullName: ISILab.LBS.AI.Categorization.MAPElitesPreset
- uid: ISILab.LBS.AI.Categorization
  commentId: N:ISILab.LBS.AI.Categorization
  isExternal: true
  href: ISILab.html
  name: ISILab.LBS.AI.Categorization
  nameWithType: ISILab.LBS.AI.Categorization
  fullName: ISILab.LBS.AI.Categorization
  spec.csharp:
  - uid: ISILab
    name: ISILab
    isExternal: true
    href: ISILab.html
  - name: .
  - uid: ISILab.LBS
    name: LBS
    isExternal: true
    href: ISILab.LBS.html
  - name: .
  - uid: ISILab.LBS.AI
    name: AI
    isExternal: true
    href: ISILab.LBS.AI.html
  - name: .
  - uid: ISILab.LBS.AI.Categorization
    name: Categorization
    isExternal: true
    href: ISILab.LBS.AI.Categorization.html
  spec.vb:
  - uid: ISILab
    name: ISILab
    isExternal: true
    href: ISILab.html
  - name: .
  - uid: ISILab.LBS
    name: LBS
    isExternal: true
    href: ISILab.LBS.html
  - name: .
  - uid: ISILab.LBS.AI
    name: AI
    isExternal: true
    href: ISILab.LBS.AI.html
  - name: .
  - uid: ISILab.LBS.AI.Categorization
    name: Categorization
    isExternal: true
    href: ISILab.LBS.AI.Categorization.html
shouldSkipMarkup: true
