### YamlMime:ManagedReference
items:
- uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme
  commentId: T:ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme
  id: LBSSettings.Interface.InterfaceTheme
  parent: ISILab.LBS.Plugin.Core.Settings
  children:
  - ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme.Alt
  - ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme.Dark
  - ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme.Darker
  - ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme.Light
  langs:
  - csharp
  - vb
  name: LBSSettings.Interface.InterfaceTheme
  nameWithType: LBSSettings.Interface.InterfaceTheme
  fullName: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme
  type: Enum
  assemblies:
  - LBS
  namespace: ISILab.LBS.Plugin.Core.Settings
  syntax:
    content: public enum LBSSettings.Interface.InterfaceTheme
    content.vb: Public Enum LBSSettings.Interface.InterfaceTheme
- uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme.Dark
  commentId: F:ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme.Dark
  id: Dark
  parent: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme
  langs:
  - csharp
  - vb
  name: Dark
  nameWithType: LBSSettings.Interface.InterfaceTheme.Dark
  fullName: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme.Dark
  type: Field
  assemblies:
  - LBS
  namespace: ISILab.LBS.Plugin.Core.Settings
  syntax:
    content: Dark = 0
    return:
      type: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme
- uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme.Light
  commentId: F:ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme.Light
  id: Light
  parent: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme
  langs:
  - csharp
  - vb
  name: Light
  nameWithType: LBSSettings.Interface.InterfaceTheme.Light
  fullName: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme.Light
  type: Field
  assemblies:
  - LBS
  namespace: ISILab.LBS.Plugin.Core.Settings
  syntax:
    content: Light = 1
    return:
      type: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme
- uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme.Alt
  commentId: F:ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme.Alt
  id: Alt
  parent: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme
  langs:
  - csharp
  - vb
  name: Alt
  nameWithType: LBSSettings.Interface.InterfaceTheme.Alt
  fullName: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme.Alt
  type: Field
  assemblies:
  - LBS
  namespace: ISILab.LBS.Plugin.Core.Settings
  syntax:
    content: Alt = 2
    return:
      type: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme
- uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme.Darker
  commentId: F:ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme.Darker
  id: Darker
  parent: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme
  langs:
  - csharp
  - vb
  name: Darker
  nameWithType: LBSSettings.Interface.InterfaceTheme.Darker
  fullName: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme.Darker
  type: Field
  assemblies:
  - LBS
  namespace: ISILab.LBS.Plugin.Core.Settings
  syntax:
    content: Darker = 3
    return:
      type: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme
references:
- uid: ISILab.LBS.Plugin.Core.Settings
  commentId: N:ISILab.LBS.Plugin.Core.Settings
  isExternal: true
  href: ISILab.html
  name: ISILab.LBS.Plugin.Core.Settings
  nameWithType: ISILab.LBS.Plugin.Core.Settings
  fullName: ISILab.LBS.Plugin.Core.Settings
  spec.csharp:
  - uid: ISILab
    name: ISILab
    isExternal: true
    href: ISILab.html
  - name: .
  - uid: ISILab.LBS
    name: LBS
    isExternal: true
    href: ISILab.LBS.html
  - name: .
  - uid: ISILab.LBS.Plugin
    name: Plugin
    isExternal: true
    href: ISILab.LBS.Plugin.html
  - name: .
  - uid: ISILab.LBS.Plugin.Core
    name: Core
    isExternal: true
    href: ISILab.LBS.Plugin.Core.html
  - name: .
  - uid: ISILab.LBS.Plugin.Core.Settings
    name: Settings
    isExternal: true
    href: ISILab.LBS.Plugin.Core.Settings.html
  spec.vb:
  - uid: ISILab
    name: ISILab
    isExternal: true
    href: ISILab.html
  - name: .
  - uid: ISILab.LBS
    name: LBS
    isExternal: true
    href: ISILab.LBS.html
  - name: .
  - uid: ISILab.LBS.Plugin
    name: Plugin
    isExternal: true
    href: ISILab.LBS.Plugin.html
  - name: .
  - uid: ISILab.LBS.Plugin.Core
    name: Core
    isExternal: true
    href: ISILab.LBS.Plugin.Core.html
  - name: .
  - uid: ISILab.LBS.Plugin.Core.Settings
    name: Settings
    isExternal: true
    href: ISILab.LBS.Plugin.Core.Settings.html
- uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme
  commentId: T:ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme
  parent: ISILab.LBS.Plugin.Core.Settings
  isExternal: true
  href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.html
  name: LBSSettings.Interface.InterfaceTheme
  nameWithType: LBSSettings.Interface.InterfaceTheme
  fullName: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme
  spec.csharp:
  - uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings
    name: LBSSettings
    isExternal: true
    href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.html
  - name: .
  - uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface
    name: Interface
    isExternal: true
    href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.html
  - name: .
  - uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme
    name: InterfaceTheme
    isExternal: true
    href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme.html
  spec.vb:
  - uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings
    name: LBSSettings
    isExternal: true
    href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.html
  - name: .
  - uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface
    name: Interface
    isExternal: true
    href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.html
  - name: .
  - uid: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme
    name: InterfaceTheme
    isExternal: true
    href: ISILab.LBS.Plugin.Core.Settings.LBSSettings.Interface.InterfaceTheme.html
shouldSkipMarkup: true
