using ISILab.AI.Grammar;
using ISILab.Commons.Attributes;
using ISILab.LBS.Components;
using ISILab.LBS.Macros;
using ISILab.LBS.Modules;
using ISILab.LBS.Plugin.Components.Data;
using ISILab.LBS.Plugin.Components.Data.Quest.Runtime;
using ISILab.LBS.Plugin.Core.Settings;
using System.Collections.Generic;
using UnityEngine;

namespace ISILab.LBS.Plugin.MapTools.Generators
{
    [RequireComponent(typeof(LBSGeneratedEventHook))]
    [RequireComponent(typeof(BoxCollider))]
    public abstract class QuestTriggerNode : QuestTrigger
    {
        #region FIELDS
        [SerializeField, ReadOnly]
        private GraphNodeType nodeType;

        private LBSGeneratedEventHook eventHooker;

        [ReadOnly]
        [SerializeField]
        private GrammarTerminal terminal;

        [SerializeField]
        protected List<GrammarField> fields = new();

        protected BoxCollider boxCillider;

        #endregion

        #region PROPERTIES
        public GrammarTerminal Terminal { get => terminal; set => terminal = value; }
        public GraphNodeType NodeType => nodeType;
        public List<GrammarField> Fields { get => fields; }
        #endregion

        #region INIT
        private void Awake()
        {

        }

        public override void InitTrigger(Node paramNode, LBSGenerator3DSettings settings, float pivotY)
        {
            var questNode = paramNode as QuestNode;
            if (questNode == null)
                return;

            // EnsureComponents();

            nodeType = questNode.NodeType;
            terminal = questNode.Data.Terminal;

            eventHooker = GetComponent<LBSGeneratedEventHook>();
            eventHooker.AssignEvents(questNode.Data.EventHooker);

            boxCillider = GetComponent<BoxCollider>();
            boxCillider.isTrigger = true;

            BindFields(questNode.Data.Fields);
            SetTriggerSize(questNode, settings, pivotY);
        }



        /// <summary>
        /// Restores the physical bounds of the trigger based on calculated area and scale.
        /// </summary>
        public void SetTriggerSize(QuestNode paramNode, LBSGenerator3DSettings settings, float pivotY)
        {
            var area = paramNode.Data.Area.value;

            float x = (area.x + area.width / 2f - 1f) * settings.scale.x;
            float z = (area.y - area.height / 2f) * settings.scale.y;

            transform.position = settings.position + new Vector3(x, pivotY, z);

            Vector3 boxSize = new Vector3(
                area.width * settings.scale.x,
                area.height * settings.scale.y,
                area.height * settings.scale.y
            );

            if (boxCillider != null)
                boxCillider.size = boxSize;
        }
        #endregion

        #region VIRTUAL/ABSTRACT METHODS
        /// <summary>
        /// This function is not meant to be overwritten manually. 
        /// It is automatically generated by <see cref="ISILab.AI.Grammar.QuestScriptGenerator"/>.
        /// </summary>
        protected abstract void BindFields(List<GrammarField> fields);

        protected virtual void OnTriggerEnter(Collider other)
        {
            if (IsPlayer(other))
                TryComplete();
        }

        protected override void Complete()
        {
            base.Complete();

            if (eventHooker != null)
                eventHooker.BroadcastEvent(LBSEventType.Complete);
        }

        public override string ToString() => Terminal.id;
        #endregion

        #region STATIC UTILITIES
        public static bool IsPlayer(Collider other) => other.CompareTag("Player");


        public static bool HasItem(Collider other, Object target, int amount = 1)
        {
            return HasItem(other, LBSAssetMacro.GetGuidFromAsset(target), amount);
        }

        public static bool HasItem(Collider other, string GUID, int amount = 1)
        {
            var inv = GetInventory(other);
            if (inv != null)
            {
                return inv.GetTypeAmount(GUID) >= amount;
            }
            return false;
        }

        public static LBSInventory GetInventory(Collider other)
        {
            return other.GetComponent<LBSInventory>();
        }
        #endregion




        #region EDITOR VALIDATION
#if UNITY_EDITOR
        /// <summary>
        /// Automatically cleans up connections in the inspector if a node's type changes.
        /// </summary>
        protected virtual void OnValidate()
        {
            // If it's a Start node, it shouldn't have previous connections
            if (nodeType == GraphNodeType.Start && Previous.Count > 0)
            {
                ClearPrevious();
            }

            // If it's a Goal node, it cannot point to a next node
            if (nodeType == GraphNodeType.Goal && Next.Count != 0)
            {
                Next.Clear();
            }
        }
#endif
        #endregion

    }
}