using ISILab.AI.Grammar;
using ISILab.LBS.Components;
using ISILab.LBS.Plugin.Components.Data;
using ISILab.LBS.Plugin.Core.Settings;
using ISILab.LBS.Plugin.MapTools.Generators;
using System.Collections.Generic;
using UnityEngine;

[RequireComponent(typeof(LBSGeneratedEventHook))]
[RequireComponent(typeof(BoxCollider))]
public abstract class QuestTriggerNode : QuestTrigger
{
    #region FIELDS
    [SerializeField, ISILab.Commons.Attributes.ReadOnly]
    private QuestNode.ENodeType nodeType;

    private LBSGeneratedEventHook eventHooker;

    [ISILab.Commons.Attributes.ReadOnly]
    [SerializeField]
    private GrammarTerminal _terminal;

    [SerializeField]
    protected List<GrammarField> _fields = new();

    protected BoxCollider BoxCollider;

    // store game objects that can be used by fields
    [SerializeField]
    private List<GameObject> gos = new();
    #endregion

    #region PROPERTIES
    public GrammarTerminal Terminal { get => _terminal; set => _terminal = value; }
    public QuestNode.ENodeType NodeType => nodeType;
    public List<GrammarField> Fields { get => _fields; }
    public List<GameObject> Gos { get => gos; set => gos = value; }
    #endregion

    #region INIT
    private void Awake()
    {
        //EnsureComponents();
    }

    public override void InitTrigger(GraphNode paramNode, LBSGenerator3DSettings settings, float pivotY)
    {
        var questNode = paramNode as QuestNode;
        if (questNode == null)
            return;

       // EnsureComponents();

        nodeType = questNode.NodeType;
        _terminal = questNode.Data.Terminal;

        if (eventHooker == null)
            eventHooker = GetComponent<LBSGeneratedEventHook>();
        eventHooker.AssignEvents(questNode.Data.EventHooker);

        BindFields(questNode.Data.Fields);
        SetTriggerSize(questNode, settings, pivotY);
    }

    private void EnsureComponents()
    {
        // 1. Try to fetch the component already added by [RequireComponent]
        if (eventHooker == null)
        {
            eventHooker = GetComponent<LBSGeneratedEventHook>();
            // Fallback fallback if it doesn't exist for some reason
            if (eventHooker == null)
                eventHooker = gameObject.AddComponent<LBSGeneratedEventHook>();
        }

        // 2. Do the exact same fallback strategy for the BoxCollider
        if (BoxCollider == null)
        {
            BoxCollider = GetComponent<BoxCollider>();
            if (BoxCollider == null)
                BoxCollider = gameObject.AddComponent<BoxCollider>();
        }

        BoxCollider.isTrigger = true;
    }

    /// <summary>
    /// Restores the physical bounds of the trigger based on calculated area and scale.
    /// </summary>
    public void SetTriggerSize(QuestNode paramNode, LBSGenerator3DSettings settings, float pivotY)
    {
        var area = paramNode.Data.Area.value;

        float x = (area.x + area.width / 2f - 1f) * settings.scale.x;
        float z = (area.y - area.height / 2f) * settings.scale.y;

        transform.position = settings.position + new Vector3(x, pivotY, z);

        Vector3 boxSize = new Vector3(
            area.width * settings.scale.x,
            area.height * settings.scale.y,
            area.height * settings.scale.y
        );

        if (BoxCollider != null)
            BoxCollider.size = boxSize;
    }
    #endregion

    #region VIRTUAL/ABSTRACT METHODS
    /// <summary>
    /// This function is not meant to be overwritten manually. 
    /// It is automatically generated by <see cref="ISILab.AI.Grammar.QuestScriptGenerator"/>.
    /// </summary>
    protected abstract void BindFields(List<GrammarField> fields);

    protected virtual void OnTriggerEnter(Collider other)
    {
        if (IsPlayer(other))
            TryComplete();
    }

    protected override void Complete()
    {
        base.Complete();

        if (eventHooker != null)
            eventHooker.BroadcastEvent(LBSEventType.Complete);
    }
    #endregion

    #region STATIC UTILITIES
    public static bool IsPlayer(Collider other) => other.CompareTag("Player");
    #endregion
}